
path: D:\PROJECTS\Python\Face Login using OpenCV  # dataset root dir
train: images/known/train  # train images (relative to 'path')
val: images/known/train  # val images (relative to 'path')

# Classes
names:
  0: ameer
  1: badri
  2: krishna
